import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BookOpen, ShieldCheck } from 'lucide-react'
import { Container } from '@/components/layout/Container'
import { ShowcaseRail } from '@/components/common/ShowcaseRail'

const paths = [['设备认知','识别印前、印刷与印后设备的职责边界。'],['工艺拆解','把纸张、色彩、装订与交期写成可核对清单。'],['项目复盘','保留需求、报价、生产与交付中的关键决策。']] as const
const media = ['/images/external/press-tools.jpg','/images/external/press-production.png','/images/external/press-studio.jpg']

export default function TrainingPage() { return <main className="bg-[#f4f2ec] pb-16"><section className="relative overflow-hidden bg-[#14263d] text-white"><Image src="/images/external/press-production.png" alt="工业印刷设备生产现场" fill priority className="object-cover opacity-35" sizes="100vw" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(20,38,61,.98),rgba(20,38,61,.78),rgba(20,38,61,.28))]"/><Container className="relative py-14 sm:py-20"><nav className="text-xs text-slate-300"><Link href="/">首页</Link><span className="mx-1.5">/</span><span>技术实训</span></nav><p className="mt-8 text-xs font-semibold uppercase tracking-[.18em] text-[#f29a70]">Print production practice</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">从设备现场到生产流程</h1><p className="mt-5 max-w-2xl text-base leading-8 text-slate-200">用来源清晰的图文资料建立工艺认知路径，并把学习结果沉淀为可复核的项目清单。</p><a href="#training-path" className="mt-7 inline-flex min-h-12 items-center gap-2 bg-[#c84f20] px-5 font-semibold text-white">进入学习路径 <ArrowRight className="size-4" /></a></Container></section><Container id="training-path" className="pt-10"><div className="grid gap-px overflow-hidden border border-[#cbd1d7] bg-[#cbd1d7] md:grid-cols-3">{paths.map(([title, detail], index) => <article key={title} className="bg-white"><div className="relative aspect-[16/8]"><Image src={media[index]} alt={`${title}实训场景`} fill className="object-cover" sizes="(min-width:768px) 33vw, 100vw" /></div><div className="p-6"><span className="font-mono text-xs font-semibold text-[#c84f20]">阶段 0{index + 1}</span><BookOpen className="mt-6 size-6 text-[#14263d]" /><h2 className="mt-4 text-lg font-bold text-[#14263d]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#5c6672]">{detail}</p></div></article>)}</div><ShowcaseRail module="training" title="工艺现场与学习资料" /><section className="mt-8 flex gap-3 border-l-4 border-[#c84f20] bg-white p-5 text-sm leading-6 text-[#5c6672]"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-[#c84f20]" /><p>图文资料均保留来源。外部课程只提供原始入口，不转载受版权保护的正文或视频。</p></section></Container></main> }
